#include <lawa/operators/convectionoperator1d.h>
#include <lawa/operators/helmholtzoperator1d.h>
#include <lawa/operators/helmholtzoperator2d.h>
#include <lawa/operators/helmholtzoperator3d.h>
#include <lawa/operators/pdeconstcoeffoperator1d.h>
#include <lawa/operators/preconditioner.h>
#include <lawa/operators/rieszoperator1d.h>
#include <lawa/operators/weaklaplaceoperator1d.h>
#include <lawa/operators/spacetimeoperators/spacetimeoperators.h>
