#include <lawa/righthandsides/function2d.h>
#include <lawa/righthandsides/homogeneousrhs.h>
//#include <lawa/righthandsides/integrals2d.h>
#include <lawa/righthandsides/rhs.h>
#include <lawa/righthandsides/rhswithpeaks1d.h>
#include <lawa/righthandsides/separablefunction2d.h>
#include <lawa/righthandsides/separablerhs2d.h>
#include <lawa/righthandsides/separablerhswithpeaks2d.h>
//#include <lawa/righthandsides/smoothrhswithalignedsing2d.h>
#include <lawa/righthandsides/sumofrhsintegrals2d.h>
#include <lawa/righthandsides/timedepseparablerhs1d.h>
