#include <lawa/methods/adaptive/operators/adaptiveidentityoperator2d.h>
#include <lawa/methods/adaptive/operators/adaptivehelmholtzoperator1d.h>
#include <lawa/methods/adaptive/operators/adaptivehelmholtzoperator2d.h>
#include <lawa/methods/adaptive/operators/adaptivehelmholtzoperatormw2d.h>
#include <lawa/methods/adaptive/operators/adaptivehelmholtzoperatorsparsemw1d.h>
#include <lawa/methods/adaptive/operators/adaptivelaplaceoperator1d.h>
#include <lawa/methods/adaptive/operators/adaptivespacetimepdeoperator1d.h>
#include <lawa/methods/adaptive/operators/diagonalpreconditioneradaptiveoperator.h>
#include <lawa/methods/adaptive/operators/weightedadaptivehelmholtzoperator2d.h>
