#include <lawa/methods/adaptive/operators/adaptiveoperator2d.h>
#include <lawa/methods/adaptive/operators/adaptivehelmholtzoperator2d.h>
#include <lawa/methods/adaptive/operators/adaptivehelmholtzoperatoroptimized1d.h>
#include <lawa/methods/adaptive/operators/adaptivehelmholtzoperatoroptimized2d.h>
#include <lawa/methods/adaptive/operators/adaptiveidentityoperator1d.h>
#include <lawa/methods/adaptive/operators/adaptiveidentityoperator2d.h>
#include <lawa/methods/adaptive/operators/adaptivelaplaceoperator1d.h>
#include <lawa/methods/adaptive/operators/diagonalpreconditioneradaptiveoperator.h>
#include <lawa/methods/adaptive/operators/weightedadaptivehelmholtzoperator2d.h>
#include <lawa/methods/adaptive/operators/spacetimeoperators/spacetimeoperators.h>
