#include <lawa/box/boxproblem.h>
#include <lawa/box/evaluate.h>
#include <lawa/box/helmholtzoperator.h>
#include <lawa/box/scalfactorpreconditioner.h>
#include <lawa/box/separablefunction.h>
#include <lawa/box/separablerhs.h>
#include <lawa/box/separablerhswithpeaks.h>
#include <lawa/box/spacetimeheatoperator.h>
#include <lawa/box/sparsetensorbasis.h>
#include <lawa/box/tensorbasis.h>
