#ifndef LAWA_CONSTRUCTIONS_INTERVAL_DKU_PRIMAL_TCC
#define LAWA_CONSTRUCTIONS_INTERVAL_DKU_PRIMAL_TCC 1

#include <lawa/constructions/interval/dku/primal/mra.tcc>

#endif // LAWA_CONSTRUCTIONS_INTERVAL_DKU_PRIMAL_TCC
